---
title: "Publication Main Figures"
author: "unawaz1996"
date: "2026-02-20"
output:
  html_notebook: default
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  
  chunk_output_type: inline
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(
    autodep = TRUE,
    eval = TRUE,
	echo = TRUE,
	warning = FALSE,
	message = FALSE
)
```


# Introduction

```{r load}
source(here::here("code/plots.R"))
source(here::here("code/functions.R"))
source(here::here("code/libraries.R"))
library(biomaRt)
library(nVennR)
library(eulerr)
library(ggsci)
library(janitor)
library(ggside)
library(ggstatsplot)
library(stargazer)
library(coin)
library(GeneOverlap)
```

```{r}
txdf = transcripts(EnsDb.Mmusculus.v79, return.type="DataFrame")
tx2gene = as.data.frame(txdf[,c("tx_id","gene_id", "tx_biotype")])
```


## Figure 2 

```{r}
load(here::here("output/DEG-list.Rda"))
```


### Figure 2a

```{r}
DEColours <- c("Downregulated" = "#53A08E","Upregulated" = "#690020",  "Not Sig" = "#CECCCA")

fc_thr <- log2(1.5)


contrast_labeller <- as_labeller(c(
  "UPF3B_vs_Control" = "italic(Upf3b)~'KD DEGs'",
  "UPF3A_vs_Control"= "italic(Upf3a)~'KD DEGs'",
  "DoubleKD_vs_Control"    = "italic(Upf3)~'dKD DEGs'",
  "UPF3A_OE_UPF3B_KD_vs_Control" = "italic(Upf3a)~'OE'~italic(Upf3b)~'KD DEGs'"
), label_parsed)



df = res %>% 
  do.call("rbind", .) %>%
    mutate(Result = ifelse(adj.P.Val < 0.05 & logFC > log2(1.5), "Upregulated",        
               ifelse(adj.P.Val < 0.05 & logFC <  -log2(1.5), "Downregulated", "Not Sig"))) %>% 
  dplyr::filter(contrast != "UPF3A_OE_vs_Control") %>%
  mutate(contrast = factor(contrast, levels= c("UPF3B_vs_Control",
                                               "UPF3A_vs_Control",
                                               "DoubleKD_vs_Control",
                                               "UPF3A_OE_UPF3B_KD_vs_Control")))

contrasts = c("UPF3B_vs_Control","UPF3A_vs_Control"        , "UPF3A_OE_vs_Control", "DoubleKD_vs_Control"         , "UPF3A_OE_UPF3B_KD_vs_Control")



deg_volcano_plot = df %>% 
    ggplot(aes(x= logFC,
               y = -log10(adj.P.Val),
               colour = as.factor(as.character(Result )))) +
    geom_point(alpha = 0.75, size = 4) +
    scale_colour_manual(values = DEColours) + theme_bw() +
  #    geom_text(
  #   data = counts,
  #   aes(x = x, y = y, label = label, colour = Result),
  #   inherit.aes = FALSE,
  #   family = "serif",
  #   size = 5
  # ) +
  xlab(bquote(log["2"](FC))) +
  ylab(bquote(-log["10"]("adjusted P-value"))) +
   scale_colour_manual(
    values = DEColours,
    breaks = c("Upregulated", "Downregulated"),
    drop = TRUE
  ) +
  guides(colour = guide_legend(override.aes = list(size = 5, alpha = 1))) +
  theme_bw() + geom_vline(xintercept = c(-log2(1.5),log2(1.5)), linetype = "dashed") +
  theme(
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size = 22), 
    legend.background = element_rect(fill = "white", colour = "black", linewidth = 0.25),
    legend.box.background = element_rect(fill = NA, colour = "black", linewidth = 0.25),
    legend.key = element_rect(fill = "white", colour = NA),

    axis.text = element_text(family = "serif", size = 25, color = "black"),
    axis.title = element_text(family = "serif", size = 22, color = "black"),
    strip.text = element_text(family = "serif", size = 20)
  ) + facet_grid(~contrast, scales =  "free_x", labeller = contrast_labeller) +  ylim(0, 10)
 
 
deg_volcano_plot      

ggsave(plot = deg_volcano_plot, filename = here::here("output/Figures/Main/DEG_volcano_fig2a.png"),
       dpi =1200, height = 6, width =18)

```

```{r}
deg_summary <- res %>%
  do.call("rbind", .) %>%
  mutate(Result = ifelse(adj.P.Val < 0.05 & logFC > log2(1.5), "Upregulated",
                   ifelse(adj.P.Val < 0.05 & logFC < -log2(1.5), "Downregulated", "Not Sig"))) %>%
  dplyr::filter(Result != "Not Sig") %>%
  dplyr::count(contrast, Result) %>%
  tidyr::pivot_wider(names_from = Result, values_from = n, values_fill = 0) %>%
  dplyr::mutate(Total_DEGs = Upregulated + Downregulated) %>%
  dplyr::arrange(match(contrast, c(
    "UPF3B_vs_Control", "UPF3A_vs_Control", "UPF3A_OE_vs_Control",
    "DoubleKD_vs_Control", "UPF3A_OE_UPF3B_KD_vs_Control"
  )))

DT::datatable(deg_summary, caption = "Number of DEGs per comparison (FDR < 0.05, |log2FC| > log2(1.5))")
```

### Figure 2b


```{r}
contrasts = c("UPF3B_vs_Control","UPF3A_vs_Control"        , "UPF3A_OE_vs_Control", "DoubleKD_vs_Control"         , "UPF3A_OE_UPF3B_KD_vs_Control")

for_upf3b =  contrasts[-c(1,3)]

overlap_upf3b = list()
for (c in for_upf3b ){
  overlap = DEGenes$UPF3B_vs_Control %>% 
    inner_join(DEGenes[[c]] , by="EnsID") %>% 
      mutate(Label = ifelse(logFC.x > 0 & logFC.y >0 | 
                            logFC.x < 0 & logFC.y <0, "Concordance", "Discordant")) 
  total = table(overlap$Label) %>% as.data.frame() 
  overlap_upf3b[[paste0(c, "_vs_Upf3b_KD")]] = total
  
}

for_upf3a = contrasts[c(4:5)]
overlap_upf3a = list()
for (c in for_upf3a ){
  overlap = DEGenes$UPF3A_vs_Control %>% 
    inner_join(DEGenes[[c]], by="EnsID") %>% 
      mutate(Label = ifelse(logFC.x > 0 & logFC.y >0 | 
                            logFC.x < 0 & logFC.y <0, "Concordance", "Discordant")) 
  total = table(overlap$Label) %>% as.data.frame() 
  overlap_upf3a[[paste0(c, "_vs_Upf3A_KD")]] = total
  
}


for_dkDupf3 = contrasts[c(5)]
overlap_dkDupf3 = list()
for (c in for_dkDupf3 ){
  overlap = DEGenes$DoubleKD_vs_Control %>% 
    inner_join(DEGenes[[c]], by="EnsID") %>% 
      mutate(Label = ifelse(logFC.x > 0 & logFC.y >0 | 
                            logFC.x < 0 & logFC.y <0, "Concordance", "Discordant")) 
  total = table(overlap$Label) %>% as.data.frame() 
  overlap_dkDupf3 [[paste0(c, "_vs_Upf3_dKD")]] = total
  
}



overlap_upf3b =do.call("rbind",overlap_upf3b) %>% 
  rownames_to_column("Comparisons") %>% 
   mutate_at(.vars = "Comparisons", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") 
  

overlap_upf3a =do.call("rbind",overlap_upf3a) %>% 
  rownames_to_column("Comparisons") %>% 
   mutate_at(.vars = "Comparisons", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") 


overlap_dkDupf3  =do.call("rbind",overlap_dkDupf3 ) %>% 
  rownames_to_column("Comparisons") %>% 
   mutate_at(.vars = "Comparisons", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") 


all_comparisons = rbind(overlap_upf3b,overlap_upf3a, overlap_dkDupf3) %>% 
  mutate(Var1 = factor(Var1, levels = c("Discordant", "Concordance" )), 
         Comparisons = factor(Comparisons, levels = c("UPF3A_OE_UPF3B_KD_vs_Control_vs_Upf3_dKD", 
                                                      "UPF3A_OE_UPF3B_KD_vs_Control_vs_Upf3A_KD",
                                                       "DoubleKD_vs_Control_vs_Upf3A_KD", 
                                                      "UPF3A_OE_UPF3B_KD_vs_Control_vs_Upf3b_KD",
                                                        "DoubleKD_vs_Control_vs_Upf3b_KD",
                                                      "UPF3A_vs_Control_vs_Upf3b_KD"
                                                      ) )) %>%
  ggplot(aes(x = Comparisons, y = Freq, fill = Var1)) + 
  geom_bar(stat= "identity", width= 0.65) + coord_flip() + scale_fill_manual(values = c( "#BAB8B5","#EB635E")) +
  theme_bw() +
     theme(axis.text.x = element_text(size = 20, family = "serif", color = "black"),
            axis.text.y = element_text(size = 20, family = "serif", color = "black"),
        axis.title = element_text(size=18, family = "serif"), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif", size=12), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =20),         
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1 ),
              legend.position = "top",
        strip.text.y = element_text(
        size = 10, face = "bold.italic", family = "serif"
        ),
         strip.text.x = element_text(
        size = 10, family = "serif"
        )) + labs(y= "Number of Overlapping transcripts",
                  fill = "Expression", 
                  x= "") + 
   scale_x_discrete(labels = c(
    "UPF3A_vs_Control_vs_Upf3b_KD" = "Upf3b KD DEGs,\nUpf3a KD DEGs",
    "DoubleKD_vs_Control_vs_Upf3b_KD" = "Upf3b KD DEGs,\nUpf3 dKD DEGs",
    "UPF3A_OE_UPF3B_KD_vs_Control_vs_Upf3b_KD" = "Upf3b KD DEGs,\nUpf3a OE — Upf3b KD\nDEGs",
    "DoubleKD_vs_Control_vs_Upf3A_KD" = "Upf3a KD DEGs, \nUpf3 dKD DEGs",
    "UPF3A_OE_UPF3B_KD_vs_Control_vs_Upf3A_KD" = "Upf3a KD DEGs,\nUpf3a OE — Upf3b KD\nDEGs", 
    "UPF3A_OE_UPF3B_KD_vs_Control_vs_Upf3_dKD" = "Upf3 dKD DEGs,\nUpf3a OE — Upf3b KD\nDEGs"
    
  ))
all_comparisons 

ggsave(filename = here::here("output/Figures/Main/DEGs-overlap-enrichment-fig2b.png"), plot = all_comparisons, dpi = 1200,
       units = c("in"), height = 10, width = 6)
```

```{r}
library(GeneOverlap)

enrichment_DEGs_P = list()
enrichment_DEGs_OR = list()


test.list = list()
test.list$UPF3B_vs_Control = DEGenes$UPF3B_vs_Control$EnsID
test.list$UPF3A_vs_Control = DEGenes$UPF3A_vs_Control$EnsID
test.list$DoubleKD_vs_Control = DEGenes$DoubleKD_vs_Control$EnsID
test.list$UPF3A_OE_UPF3B_KD_vs_Control = DEGenes$UPF3A_OE_UPF3B_KD_vs_Control$EnsID
test.list$BG = res$UPF3B_vs_Control$EnsID

for_upf3b = contrasts[-c(1,3)]

for (c in for_upf3b ){
  
  go.obj <- newGeneOverlap(test.list$UPF3B_vs_Control, 
                         test.list[[c]],
                         genome.size=length(test.list$BG))
  go.obj <- testGeneOverlap(go.obj)
  enrichment_DEGs_P[[paste0("Upf3b_KD", "_", c)]] = go.obj@pval
  enrichment_DEGs_OR[[paste0("Upf3b_KD", "_", c)]] = go.obj@odds.ratio 
}
  
for_upf3a = contrasts[c(4:5)]

for (c in for_upf3a ){
    go.obj <- newGeneOverlap(test.list$UPF3A_vs_Control, 
                         test.list[[c]],
                         genome.size=length(test.list$BG))
  go.obj <- testGeneOverlap(go.obj)
  enrichment_DEGs_P[[paste0("Upf3a_KD", "_", c)]] = go.obj@pval
  enrichment_DEGs_OR[[paste0("Upf3a_KD", "_", c)]] = go.obj@odds.ratio 
}


for_dkDupf3 = contrasts[c(5)]
for (c in for_dkDupf3 ){
      go.obj <- newGeneOverlap(test.list$DoubleKD_vs_Control, 
                         test.list[[c]],
                         genome.size=length(test.list$BG))
  go.obj <- testGeneOverlap(go.obj)
  enrichment_DEGs_P[[paste0("Upf3_dKD", "_", c)]] = go.obj@pval
  enrichment_DEGs_OR[[paste0("Upf3_dKD", "_", c)]] = go.obj@odds.ratio 
  
}

enrichment_DEGs_OR %>% do.call(rbind,.) %>% 
  set_colnames("OR") %>% 
  cbind(enrichment_DEGs_P %>% do.call(rbind,.) %>% set_colnames("pvalue")) %>% 
  as.data.frame()  %>% DT::datatable()
```


### Figure 2c

```{r fig.height=4, fig.width=8}
cor_upf3a_upf3b =  DEGenes$UPF3B_vs_Control %>% 
  
  inner_join(DEGenes$UPF3A_vs_Control,  by = "EnsID") %>% 
  mutate(Label = ifelse(logFC.x > 0 & logFC.y >0 | 
                            logFC.x < 0 & logFC.y <0, "Concordance", "Discordant")) %>% 
  ggscatter(., x= "logFC.x", y="logFC.y", 
              cor.coef = TRUE, add = "reg.line", 
              cor.coeff.args = list(size = 6, family = "serif",  label.y = 6), 
              size=5, alpha =0.75, color = "Label",
              conf.int = TRUE, add.params = list(color = "blue",
                                                 fill = "lightgray")) + 
    theme_bw() + ylab(expression(italic("Upf3a") ~ "KD (LFC)")) +
xlab(expression(italic("Upf3b") ~ "KD (LFC)")) +
  geom_hline(yintercept = 0, size = 0.5,lty = "dashed", color = "grey60") +
  geom_vline(xintercept = 0, size = 0.5, lty = "dashed", color = "grey60") + theme(legend.position = "none") +
  scale_color_manual(values = c("#EB635E", "#BAB8B5")) +  
  theme(axis.text.x = element_text(size = 20, family = "serif", color = "black"),
            axis.text.y = element_text(size = 20, family = "serif", color = "black"),
        axis.title = element_text(size=24, family = "serif"), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif"), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =20),         
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1 ),
              legend.position = "none",
        strip.text.y = element_text(
        size = 10, face = "bold.italic", family = "serif"
        ),
         strip.text.x = element_text(
        size = 10, family = "serif"
        )) + labs(color = "Expression")



cor_upf3b_upf3d =  DEGenes$UPF3B_vs_Control %>% 
  
  inner_join(DEGenes$DoubleKD_vs_Control,  by = "EnsID") %>% 
  mutate(Label = ifelse(logFC.x > 0 & logFC.y >0 | 
                            logFC.x < 0 & logFC.y <0, "Concordance", "Discordant")) %>% 
  ggscatter(., x= "logFC.x", y="logFC.y", 
              cor.coef = TRUE, add = "reg.line", 
              size=5, alpha =0.75, color = "Label",
            cor.coeff.args = list(size = 6, family = "serif",  label.y = 7.5), 
              conf.int = TRUE, add.params = list(color = "blue",
                                                 fill = "lightgray")) + 
    theme_bw() + ylab(expression(italic("Upf3") ~ "dKD (LFC)")) +
xlab(expression(italic("Upf3b") ~ "KD (LFC)")) +
  geom_hline(yintercept = 0, size = 0.5,lty = "dashed", color = "grey60") +
  geom_vline(xintercept = 0, size = 0.5, lty = "dashed", color = "grey60") + theme(legend.position = "none") +
  scale_color_manual(values = c("#EB635E", "#BAB8B5")) +  
  theme(axis.text.x = element_text(size = 20, family = "serif", color = "black"),
            axis.text.y = element_text(size = 20, family = "serif", color = "black"),
        axis.title = element_text(size=24, family = "serif"), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif"), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =20),         
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1 ),
              legend.position = "none",
        strip.text.y = element_text(
        size = 10, face = "bold.italic", family = "serif"
        ),
         strip.text.x = element_text(
        size = 10, family = "serif"
        )) + labs(color = "Expression")






cor_upf3a_upf3d =  DEGenes$UPF3A_vs_Control %>% 
  
  inner_join(DEGenes$DoubleKD_vs_Control,  by = "EnsID") %>% 
  mutate(Label = ifelse(logFC.x > 0 & logFC.y >0 | 
                            logFC.x < 0 & logFC.y <0, "Concordance", "Discordant")) %>% 
  ggscatter(., x= "logFC.x", y="logFC.y", 
              cor.coef = TRUE, add = "reg.line", 
              size=5, alpha =0.75, color = "Label",
            cor.coeff.args = list(size = 6, family = "serif",  label.y = 7.5),
              conf.int = TRUE, add.params = list(color = "blue",
                                                 fill = "lightgray")) + 
    theme_bw() +ylab(expression(italic("Upf3") ~ "dKD (LFC)")) +
xlab(expression(italic("Upf3a") ~ "KD (LFC)")) +
  geom_hline(yintercept = 0, size = 0.5,lty = "dashed", color = "grey60") +
  geom_vline(xintercept = 0, size = 0.5, lty = "dashed", color = "grey60") + theme(legend.position = "none") +
  scale_color_manual(values = c("#EB635E", "#BAB8B5")) +  
  theme(axis.text.x = element_text(size = 20, family = "serif", color = "black"),
            axis.text.y = element_text(size = 20, family = "serif", color = "black"),
        axis.title = element_text(size=24, family = "serif"), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif"), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =20),         
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1 ),
              legend.position = "none",
        strip.text.y = element_text(
        size = 10, face = "bold.italic", family = "serif"
        ),
         strip.text.x = element_text(
        size = 10, family = "serif"
        )) + labs(color = "Expression")




Upf3b_oR_cor = DEGenes$UPF3B_vs_Control %>% 
  #rownames_to_column("EnsID") %>% 
  
  inner_join(DEGenes$UPF3A_OE_UPF3B_KD_vs_Control, #%>% 
              # rownames_to_column("EnsID"),
             by = "EnsID") %>% 
  mutate(Label = ifelse(logFC.x > 0 & logFC.y >0 | 
                            logFC.x < 0 & logFC.y <0, "Concordant", "Discordant")) %>% 
  ggscatter(., x= "logFC.x", y="logFC.y", 
              cor.coef = TRUE, add = "reg.line", 
              size=5, alpha =0.75, color = "Label",
            cor.coeff.args = list(size = 6, family = "serif", label.y = 5.5), 
              conf.int = TRUE, add.params = list(color = "blue",
                                                 fill = "lightgray")) + 
    theme_bw() + 
  ylab(expression(italic("Upf3a") ~ "OE -" ~ italic("Upf3b") ~ "KD (LFC)")) +
  xlab(expression(italic("Upf3b") ~ "KD (LFC)")) +
  geom_hline(yintercept = 0, size = 0.5,lty = "dashed", color = "grey60") +
  geom_vline(xintercept = 0, size = 0.5, lty = "dashed", color = "grey60") + theme(legend.position = "none") +
  scale_color_manual(values = c("#EB635E", "#BAB8B5")) +  
  theme(axis.text.x = element_text(size = 20, family = "serif", color = "black"),
            axis.text.y = element_text(size = 20, family = "serif", color = "black"),
        axis.title = element_text(size=24, family = "serif"), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif"), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =20),         
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1 ),
              legend.position = "none",
        strip.text.y = element_text(
        size = 10, face = "bold.italic", family = "serif"
        ),
         strip.text.x = element_text(
        size = 10, family = "serif"
        )) + labs(color = "Expression")





ggarrange(cor_upf3a_upf3b, cor_upf3b_upf3d,
          cor_upf3a_upf3d, Upf3b_oR_cor, ncol =4, common.legend = TRUE)

```

```{r}

ggsave(filename = here::here("output/Figures/Main/Upf3b-Upf3a-cor-fig2c.png"), plot = cor_upf3a_upf3b , dpi = 1200,
       units = c("in"), height = 7.5, width = 4)


ggsave(filename = here::here("output/Figures/Main/Upf3b-Upf3dKD-cor-fig2c.png"), plot = cor_upf3b_upf3d , dpi = 1200,
       units = c("in"), height = 7.5, width = 4)
ggsave(filename = here::here("output/Figures/Main/Upf3a-Upf3dKD-cor-fig2c.png"), plot = cor_upf3a_upf3d , dpi = 1200,
       units = c("in"), height = 7.5, width = 4)


ggsave(filename = here::here("output/Figures/Main/Upf3b-Upf3aOEUpf3bKD-cor-fig2c.png"), plot = Upf3b_oR_cor , dpi = 1200,
       units = c("in"), height = 7.5, width = 4)
```

### Figure 2e

```{r}
load(file=here::here("output/DET-list.Rda"))
```

```{r}
NMD_features = read.table(here::here("data/nif_output/Mus_musculus__nifs.tsv"), sep = "\t", skip =1)

colnames(NMD_features)[1:4] = c("EnsID", "NIF_dEJ", "NIF_uORF", "NIF_long-3'utr")
NMD_features = NMD_features[,1:4]
tx_NMD = NMD_features %>%
  mutate_at(.vars = "EnsID", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>%
  dplyr::rename("tx_id" = "EnsID") %>%
  right_join(dge.scaled.filtr$counts %>%
               as.data.frame() %>%
               rownames_to_column("tx_id") %>%
               mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = ""),
             by="tx_id")

dEJ = tx_NMD %>%
  dplyr::filter(NIF_dEJ == "True") %>%
  dplyr::select(tx_id)


uORF = tx_NMD %>%
  dplyr::filter(NIF_uORF == "True") %>%
  dplyr::select(tx_id)
UTR = tx_NMD %>%
  dplyr::filter(`NIF_long-3'utr` == "True") %>%
  dplyr::select(tx_id)

x = list( "dEJ" = dEJ$tx_id,
          "uORF" = uORF$tx_id,
          "Long 3'UTR" = UTR$tx_id,
          "All transcripts" = tx_NMD$tx_id)

UpSetR::upset(fromList(x), main.bar.color = c("#585A58", "#6d597a", "#eaac8b", "#fcb9b2",
                                              "#585A58", "#585A58", "#585A58", "#585A58"),
              sets.bar.color = c("#585A58", "#6d597a", "#eaac8b", "#fcb9b2"),
                  mainbar.y.label = "Overlap of Transcripts with NMD inducing features",
              sets.x.label = "Number of transcripts",
                text.scale = c(0.8,1.2,1.2, 1.2, 1.2),
              point.size = 4.3)

```

### Figure 2f

```{r}
nif_features = list()
for (i in names(res_dte)[-3]){
  name = i
  temp = res_dte[[i]]
  
  message("Counting NIFs in upregulated transcripts for ", name)
  sig_up = temp %>%  as.data.frame() %>%  
        dplyr::filter(FDR < 0.05, logFC > log2(1)) 
  utr = table(sig_up$NIF_long_3utr)[2]
  dej = table(sig_up$NIF_dEJ)[2]
  uorf = table(sig_up$NIF_uORF)[2]
  none = table(sig_up$nif_feature)[1]
  total_nif_up  = rbind(utr, dej, uorf, none) %>% 
    as.data.frame() %>% 
    rownames_to_column("NIF_feature") %>% 
    mutate(Condition = name, 
           Expression = "Up") %>% 
    dplyr::rename("Count" = "1")
  
  message("Counting NIFs in downregulated transcripts for ", name)
  
  sig_down = temp %>%  as.data.frame() %>%  
        dplyr::filter(FDR < 0.05, logFC < log2(1)) 
  utr = table(sig_down$NIF_long_3utr)[2]
  dej = table(sig_down$NIF_dEJ)[2]
  uorf = table(sig_down$NIF_uORF)[2]
   none = table(sig_down$nif_feature)[1]
  total_nif_down  = rbind(utr, dej, uorf, none) %>% 
    as.data.frame() %>% 
    rownames_to_column("NIF_feature") %>% 
    mutate(Condition = name, 
           Expression = "Down") %>% 
    dplyr::rename("Count" = "1")
  
  nif_features= rbind(nif_features, total_nif_up, total_nif_down, stringsAsFactors = FALSE)
  
}

OE_df = data.frame("NIF_feature" = "")

### For overexprssion - up
## 0 for long 3'UTR
## 0 for dEJ 
## 1 for uORF

### down 
## 3 long utr
## 0 dej
### 1 for uORF

OE_df = data.frame("NIF_feature" = rep(c("utr", "dej", "uorf"), 2), 
                   "Count" = c(0,0, 1,3,0, 1), 
                   "Condition" = rep(c("UPF3A_OE_Control")),
                   "Expression" = c(rep("Up",3), rep("Down", 3)))

nif_features= rbind(nif_features, OE_df, stringsAsFactors = FALSE)


condition.labs <- c("Upf3b KD", "Upf3a KD", "Upf3 dKD", "Upf3a OE", "Upf3a OE, Upf3b KD")
names(condition.labs) <- c("UPF3B_KD", "UPF3A_KD", "UPF3A_KD_UPF3B_KD",
                      "UPF3A_OE", "UPF3A_OE_UPF3B_KD") 
nif_number = nif_features %>%
  mutate(NIF_feature = gsub("utr", "Long 3'UTR", NIF_feature), 
         NIF_feature = gsub("uorf", "Upstream ORF", NIF_feature), 
         NIF_feature = gsub("dej", "Downstream exon junction", NIF_feature), 
         Condition = gsub("_Control", "", Condition)) %>%
  mutate(Condition = factor(Condition, levels = c("UPF3B_KD",
                                                  "UPF3A_KD", 
                                                  "UPF3A_KD_UPF3B_KD", 
                                                  "UPF3A_OE",
                                                  "UPF3A_OE_UPF3B_KD")), 
         Expression = factor(Expression, levels = c("Down", "Up")),
          NIF_feature = factor(NIF_feature, levels = c("none",
                                                             
                                                             "Upstream ORF",
                                                             "Long 3'UTR",
                                                       "Downstream exon junction"))) %>%
  
  ggplot(aes(x= NIF_feature, y = Count, fill = Expression)) + 
  geom_bar(stat = "identity", position = "stack", width = .5) + coord_flip() + 
  theme_bw() +
  facet_grid(~Condition,
             labeller = labeller(Condition = condition.labs))  +
  xlab("") + ylab("") + scale_fill_manual(values = c("Up"= "#b23a48",
                                                     "Down" = "grey")) + 
   
     theme(axis.text.x = element_text(size = 12, family = "serif", color = "black", angle = 90),
        axis.text.y = element_text(size = 12, family = "serif", color = "black"), 
        axis.title = element_text(size=15, family = "serif"), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif"), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =20),         
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1 ),
              legend.position = "top",
         strip.text.x = element_text(
        size = 12, face = "bold.italic", family = "serif"
        ))

nif_number
ggsave(filename = "/home/neuro/Documents/NMD_analysis/Analysis/NMD-analysis/output/Figures/Main/Count_NIF_2f.png",
       plot = nif_number  ,  units = c("in"), height = 5, width = 14)
```

```{r}
nif_features %>%
  mutate(NIF_feature = gsub("utr", "Long 3'UTR", NIF_feature), 
         NIF_feature = gsub("uorf", "Upstream ORF", NIF_feature), 
         NIF_feature = gsub("dej", "Downstream exon junction", NIF_feature), 
         Condition = gsub("_Control", "", Condition))
```

## Figure 3


### Figure 3a

```{r}
load(here::here("output/Stability/differential-stability.Rda"))
```

```{r}
upf3b_res = z[[2]]

upf3b_res %>%
  dplyr::filter(padj < 0.05) %>%
  with(., table(sign(log2FoldChange)))

DEColours <- c("Destabilized" = "#2F124B","Stabilised" = "#ee6c4d",  "Not significant" = "#D3D5E3", "NA" = "#D3D5E3")
volc = upf3b_res %>%
   mutate(results = ifelse(log2FoldChange> 0 & padj < 0.05, "Stabilised",
                           ifelse(padj < 0.05 & log2FoldChange < 0, "Destabilized", "Not significant"))) %>%
  drop_na("results") %>%
    ggplot(aes(x = log2FoldChange, 
               y = -log10(padj), 
               colour = as.factor(as.character(results )))) +
    geom_point(alpha = 0.8, size =3) +
    scale_colour_manual(values = DEColours) + theme_classic() +
    geom_hline(yintercept = -log10(0.05), color = "grey60", size = 0.5, lty = "dashed") +
    xlab(bquote(log["2"](FC))) +
  ylab(bquote(-log["10"]("adjusted P-value"))) +
  
  #  labs(x = "log2 Fold Change", y = "-log10 adj p-value") +
  #  ggtitle("Upf3b KD differentially stabilised genes") + 
  geom_vline(xintercept = 0, size = 0.5, lty = "dashed", color = "grey60") + xlim(-3, 3) + 
  ylim(0,7.5) +
        theme(axis.text.x = element_text(size = 25, family = "serif", color = "black"),
              axis.text.y = element_text(size = 25, family = "serif", color = "black"),
        axis.title = element_text(size=25, family = "serif"), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif", size = 15), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =15),
        legend.position = "top"
        )  + labs(color = "") 

volc
ggsave(filename = "/home/neuro/Documents/NMD_analysis/Analysis/NMD-analysis/output/Figures/Main/Upf3b-stability_fig3a.png", plot = volc,  units = c("in"), height = 6, width = 6, dpi =1200)


```

### Figure 3b


```{r fig.width=8, fig.height=8, fig.cap="Overlap of DEG and DSA analysis from differential stability estimates"}
upf3b_res = z[[2]] %>% as.data.frame() %>%
  dplyr::filter(padj < 0.05) %>% 
  #rownames_to_column("EnsID") %>% 
    mutate(gene = mapIds(org.Mm.eg.db, keys=EnsemblID,  column="SYMBOL",keytype="ENSEMBL", multiVals="first"), 
           entrez = mapIds(org.Mm.eg.db, keys=EnsemblID,  column="ENTREZID",keytype="ENSEMBL", multiVals="first"),
           type =  mapIds(org.Mm.eg.db, keys=EnsemblID,  column="GENETYPE",keytype="ENSEMBL", multiVals="first")) %>% drop_na(entrez)


x= list( "Upf3b KD DEGs" = DEGenes$UPF3B_vs_Control$EnsID, 
    "Upf3b KD DSGs" = upf3b_res$EnsemblID)


ggvenn(x[c(1,2)], fill_color = c("#2F124B", "#801D2E"),
       set_name_color = "black", text_color = "white", text_size = 10, 
       stroke_size = 0.45, fill_alpha = 0.8, 
       stroke_color = "white", show_percentage = FALSE)

 ggsave(filename = "/home/neuro/Documents/NMD_analysis/Analysis/NMD-analysis/output/Figures/Main/Upf3b-stability_overlap_fig3b.png",  units = c("in"), height = 6, width = 6, dpi =1200)
 
 
```
 
```{r}
x = calculate.overlap(x)

go.obj <- newGeneOverlap(DEGenes$UPF3B_vs_Control$EnsID, 
                         upf3b_res$EnsemblID,
                         genome.size=length(res$UPF3B_vs_Control$EnsID))
go.obj <- testGeneOverlap(go.obj)

message(paste("Odds ratio=", go.obj@odds.ratio))
message(paste("p-value=", go.obj@pval))
```

### Figure 3c

```{r}
overlapping_upf3b = DEGenes$UPF3B_vs_Control %>% 
  inner_join(upf3b_res %>% dplyr::rename(EnsID = EnsemblID ), by="EnsID") %>% 
    dplyr::rename("gene_id" = "EnsID") %>% 
    left_join(res_dte$UPF3B_KD_Control %>% 
               left_join(tx2gene) %>% 
               dplyr::filter(FDR < 0.05),by = "gene_id") %>%
   mutate(nif= ifelse(nif_feature == "None" | is.na(nif_feature),"NIF-", "NIF+"))

overlap_DSA = overlapping_upf3b %>%  
  distinct(gene_id, .keep_all = TRUE) %>%
  ggscatter(.,x="logFC.x", y ="log2FoldChange", cor.coef = TRUE, add = "reg.line",
              conf.int = TRUE, color = "nif", 
            cor.coeff.args = list(size = 7, family = "serif"), 
            add.params = list(color = "blue",
                                                 fill = "lightgray"), alpha =0.8, shape = "nif", size =3) + 
    theme_bw() + 
  #ylab("Upf3b DSG (log2FC)") +   scale_color_manual(values = c("#F15A2B", "#2E368F")) + 
    geom_hline(yintercept = 0, size = 0.5,lty = "dashed", color = "grey60") +
  geom_vline(xintercept = 0, size = 0.5, lty = "dashed", color = "grey60") + theme(legend.position = "none") +
  theme(axis.text.x = element_text(size = 15, family = "serif", color = "black"),
            axis.text.y = element_text(size = 15, family = "serif", color = "black"),
        axis.title = element_text(size=22, family = "serif"), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif"), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =20),         
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1 ),
              legend.position = "top",
        strip.text.y = element_text(
        size = 10, face = "bold.italic", family = "serif"
        ),
         strip.text.x = element_text(
        size = 10, family = "serif"
        )) + labs(color = "Expression") + geom_xsideboxplot(aes(y = nif, fill= nif), orientation = "y") +
   theme(ggside.panel.scale = .3) +
  scale_xsidey_discrete()  + geom_ysidedensity(aes(x = after_stat(density), fill = nif), alpha = 0.5) +
  scale_color_manual(values = c("NIF+" = "#b23a48",
                                "NIF-" = "grey")) +  scale_fill_manual(values = c("NIF+" = "#b23a48",
                                "NIF-" = "grey")) + scale_shape_manual(values = c(19,15)) + labs(
  y = expression(italic(Upf3b) ~ "KD DSG (" * log[2] * "FC)"), 
  x = expression(italic(Upf3b) ~ "KD DEG (" * log[2] * "FC)"))
overlap_DSA

ggsave(filename = "/home/neuro/Documents/NMD_analysis/Analysis/NMD-analysis/output/Figures/Main/Upf3b-stability-overlap_3c.png", plot = overlap_DSA,  units = c("in"), height = 7, width = 7, dpi =1200)
```

### Figure 3d 

```{r}
non_intersect = x$a1[!x$a1 %in% x$a3]
non_overlapping_upf3b = DEGenes$UPF3B_vs_Control %>%
  dplyr::filter(EnsID %in% non_intersect) %>%
    dplyr::rename("gene_id" = "EnsID") %>%
  left_join(res_dte$UPF3B_KD_Control %>%
               left_join(tx2gene) %>%
               dplyr::filter(FDR < 0.05),by = "gene_id") %>%
  mutate(nif= ifelse(nif_feature == "None" | is.na(nif_feature),"NIF-", "NIF+"))


table(overlapping_upf3b$nif) %>%
  as.data.frame() %>%
  mutate(group = "Overlap") %>%
  rbind(table(non_overlapping_upf3b$nif) %>%
          as.data.frame() %>%
          mutate(group = "Non-overlapping"))
```

```{r}
nif_overlap = overlapping_upf3b %>% 
  distinct(gene_id, .keep_all = TRUE) %>%
  dplyr::select(nif) %>% mutate(group = "DEGs/DSGs\nOverlapping") %>% rbind(non_overlapping_upf3b %>% distinct(gene_id, .keep_all = TRUE) %>% dplyr::select(nif) %>% mutate(group = "Non-overlapping\nDEGs")) %>% mutate(nif = factor(nif, levels = c("NIF+", "NIF-"))) %>%
  ggbarstats( 
    x = nif, y = group,
    sample.size.label.args = list(size = 6), 
    label.text.size = 8, 
    #results.subtitle = FALSE, proportion.test = FALSE, 
    xlab = "", legend.title = "") + 
#ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))), ) + 
    scale_fill_manual(values = c("NIF+" = "#b23a48","NIF-" = "grey")) + 
    theme_bw() +
    labs(y="Prpoportion of transcripts") +
    theme(axis.text = element_text(color ="black", size =13), legend.box.background = element_rect(color = "black"), plot.subtitle = element_text(size = 12))

nif_overlap

 ggsave(filename = "/home/neuro/Documents/NMD_analysis/Analysis/NMD-analysis/output/Figures/Main/Upf3b-bf-NIF-proportion.png", plot = nif_overlap ,  units = c("in"), height = 6, width = 5, dpi =1200)
 
```



### Figure 3e

```{r}

upf3a_res = z[[1]] %>% as.data.frame() %>% dplyr::rename(EnsID = EnsemblID ) %>%  dplyr::filter(padj < 0.05)

overlapping_upf3a = DEGenes$UPF3A_vs_Control %>% 
  inner_join(upf3a_res, by="EnsID") %>% 
    dplyr::rename("gene_id" = "EnsID") %>% 
    left_join(res_dte$UPF3A_KD_Control %>% 
               left_join(tx2gene) %>% 
               dplyr::filter(FDR < 0.05),by = "gene_id") %>%
   mutate(nif= ifelse(nif_feature == "None" | is.na(nif_feature) ,"NIF-", "NIF+"))

upf3dKD_res = z[[3]] %>% as.data.frame() %>% dplyr::rename(EnsID = EnsemblID ) %>%  dplyr::filter(padj < 0.05)
overlapping_upf3dKD = DEGenes$DoubleKD_vs_Control %>% 
  inner_join(upf3dKD_res, by="EnsID") %>% 
    dplyr::rename("gene_id" = "EnsID") %>% 
    left_join(res_dte$UPF3A_KD_UPF3B_KD_Control %>% 
               left_join(tx2gene) %>% 
               dplyr::filter(FDR < 0.05),by = "gene_id") %>%
   mutate(nif= ifelse(nif_feature == "None" |is.na(nif_feature),"NIF-", "NIF+"))

```


```{r}
DD_NMD_candidates = list()

DD_NMD_candidates$Upf3b = overlapping_upf3b %>% 
  dplyr::filter(logFC.x > 0) %>% 
   dplyr::filter(nif == "NIF+")


DD_NMD_candidates$Upf3a = overlapping_upf3a %>% 
  dplyr::filter(logFC.x > 0) %>% 
   dplyr::filter(nif == "NIF+") 

DD_NMD_candidates$Upf3dKD = overlapping_upf3dKD %>% 
  dplyr::filter(logFC.x > 0) %>% 
   dplyr::filter(nif == "NIF+") 
```


```{r}
x= list( "Upf3b KD" = DD_NMD_candidates$Upf3b$gene_id, 
    "Upf3a KD" =DD_NMD_candidates$Upf3a$gene_id,
    "Upf3 dKD" = DD_NMD_candidates$Upf3dKD$gene_id)

ggvenn(x, fill_color = c("#1c174a", "#ef476f", "#7175b3"),
       set_name_color = "black", text_color = "white", text_size = 5, 
       stroke_size = 0.45, fill_alpha = 0.8, 
       stroke_color = "white", show_percentage = FALSE)


 ggsave(filename = "/home/neuro/Documents/NMD_analysis/Analysis/NMD-analysis/output/Figures/Main/DD-NMD-overlap_fig3e.png",  units = c("in"), height = 8, width = 6, dpi =1200)
```

```{r}
overlaps = calculate.overlap(x)
```

```{r}
go.obj <- newGeneOverlap(DD_NMD_candidates$Upf3b$gene_id, 
                         DD_NMD_candidates$Upf3a$gene_id,
                         genome.size=length(res$UPF3A_vs_Control$EnsID))
go.obj <- testGeneOverlap(go.obj)

message(paste("Odds ratio=", go.obj@odds.ratio))
message(paste("p-value=", go.obj@pval))

```

```{r}
go.obj <- newGeneOverlap(DD_NMD_candidates$Upf3dKD$gene_id, 
                         DD_NMD_candidates$Upf3a$gene_id,
                         genome.size=length(res$UPF3A_vs_Control$EnsID))
go.obj <- testGeneOverlap(go.obj)

message(paste("Odds ratio=", go.obj@odds.ratio))
message(paste("p-value=", go.obj@pval))
```

```{r}
go.obj <- newGeneOverlap(DD_NMD_candidates$Upf3dKD$gene_id, 
                         DD_NMD_candidates$Upf3b$gene_id,
                         genome.size=length(res$UPF3A_vs_Control$EnsID))
go.obj <- testGeneOverlap(go.obj)

message(paste("Odds ratio=", go.obj@odds.ratio))
message(paste("p-value=", go.obj@pval))
```


### Figure 3f


## Figure 4


```{r}
load(here::here("output/fgsea-heatmap-data.Rda"))
```

```{r fig.height =20, fig.width= 15}
heatmap_1 =all_heatmap  |> 
  mutate(geneRatio = leSize/fgsea.size,
         Geneset = tolower(gsub("REACTOME_", "", Geneset))) |>
  mutate(Geneset = gsub("_", " ", Geneset)) |>
  dplyr::filter(Category %in%  c("Cell Cycle",
                                 "Gene expression (transcription)",
                                 "Metabolism of RNAs", 
                                 "Extracellular matrix",
                                 "Cellular responses to stimuli")) |>
  mutate(Category = factor(Category, levels =  c("Cell Cycle",
                                 "Gene expression (transcription)",
                                 "Metabolism of RNAs", 
                                 "Extracellular matrix",
                                 "Cellular responses to stimuli")),
         comparison = factor(comparison, levels = c("UPF3B_KD_vs_Control",
                                                    "UPF3A_KD_vs_Control",
                                                    "DoubleKD_vs_Control",
                                                    "UPF3A_OE_vs_Control",
                                                    "UPF3A_OE_UPF3B_KD_vs_Control"))) |>
  ggplot(aes(x = comparison, y = fct_reorder(Geneset, as.integer(Category)))) +
  geom_point(
    aes(fill = fgsea.NES, size = leSize), shape = 21
  ) +
    theme_bw() +
  theme(
    legend.position = 'top',
    text = element_text(color = 'grey40')
  )  +
  scale_fill_gradient2(low="#7CCCBE",mid="#E8C1A0", high = "#F4593E") +
  #  scale_color_manual(values = "black") +
  labs(fill = "Normalized enrichment score") +
    theme(axis.text.x = element_text(size = 12, family = "serif", color = "black", angle = 90),
        axis.title = element_text(size=15, family = "serif"), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif"), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =20),         
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1 ),
              legend.position = "top") + coord_flip()
heatmap_1 
```

```{r}
heatmap_2 = all_heatmap  |> 
  mutate(geneRatio = leSize/fgsea.size,
         Geneset = tolower(gsub("REACTOME_", "", Geneset))) |>
  mutate(Geneset = gsub("_", " ", Geneset)) |>
  dplyr::filter(Category %in%  c( "Signal Transduction",
                                 "Developmental Biology",
                                 "Metabolism of proteins",
                                 "Metabolism of Proteins",
                                 "Chromatin organization",
                                 "DNA Replication",
                                 "DNA Repair",
                                 "Disease",
                                 "Immune",
                                 "Metabolism",
                                 "Programmed Cell Death",
                                 "Autophagy"))  |>
  mutate(Category = factor(Category, levels =  c("Signal Transduction",
                                 "Developmental Biology",
                                 "Metabolism of proteins",
                                 "Metabolism of Proteins",
                                 "Chromatin organization",
                                 "DNA Replication",
                                 "DNA Repair",
                                 "Disease",
                                 "Immune",
                                 "Metabolism",
                                 "Programmed Cell Death",
                                 "Autophagy")),
         comparison = factor(comparison, levels = c("UPF3B_KD_vs_Control",
                                                    "UPF3A_KD_vs_Control",
                                                    "DoubleKD_vs_Control",
                                                    "UPF3A_OE_vs_Control",
                                                    "UPF3A_OE_UPF3B_KD_vs_Control"))) |>
  ggplot(aes(x = comparison, y =fct_reorder(Geneset, as.integer(Category)))) +
  geom_point(
    aes(fill = fgsea.NES, size = leSize), shape = 21
  ) +
    theme_bw() +
  theme(
    legend.position = 'top',
    text = element_text(color = 'grey40')
  )  +
  scale_fill_gradient2(low="#7CCCBE",mid="#E8C1A0", high = "#F4593E") +
  #  scale_color_manual(values = "black") +
  labs(fill = "Normalized enrichment score") +
    theme(#axis.text.x = element_text(size = 12, family = "serif", color = "black", angle = 90),
        axis.title = element_text(size=15, family = "serif"), 
        axis.text.y = element_text(angle = 90), 
         legend.box.background = element_rect(color = "black"),
          legend.text = element_text(family = "serif"), 
          legend.title = element_text( family = "serif"),
           plot.title = element_text(family = "serif", size =20),         
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1 ),
              legend.position = "top") + coord_flip()

heatmap_2
```
